---
abstract: 'Get source filename and line number of a subroutine'
author:
  - 'Fuji, Goro (gfx) <gfuji(at)cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  FindBin::libs: 0
  Path::Class: 0
  Test::More: 0.88
  Test::Requires: 0.06
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: UNIVERSAL::source_location_for
name: UNIVERSAL-source_location_for
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/Cside/UNIVERSAL-source_location_for.git
version: 0.02
